services:
  postgres:
    image: postgres:17-alpine
    container_name: dggac-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dggac
      POSTGRES_PASSWORD: dggac
      POSTGRES_DB: dggac
    ports:
      - '5432:5432'
    volumes:
      - dggac-postgres-data:/var/lib/postgresql/data

volumes:
  dggac-postgres-data:
